### ISSUE TITLE
nuget package doesn't install

### ISSUE THREAD

**Issue by echeloop** [denis-tsv/Microsoft.CodeAnalysis.CSharp.Extensions#1]
I get this error when trying to install using nuget package manager into the default code analyzer project:

Could not install package 'Microsoft.CodeAnalysis.CSharp.Extensions 1.0.0-rc'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by denis-tsv** [comment]
Hello!

I have updated the package. Latest version of the package is portable and supports .NET 4.5 and Windows 8 platforms. Also package used release version of Microsoft.CodeAnalysis.CSharp instead of release candidate version of Microsoft.CodeAnalysis.CSharp in previous version.
